### ISSUE TITLE
Breadcrum for View Page

### ISSUE THREAD

**Issue by GHOST117s** [Sevendays-Digital/filament-nested-resources#5]
foreach ($resource::getParentTree(static::getResource()::getParent(), $this->urlParameters) as $nested) {
            $nestedCrumbs[$nested->getEditUrl()] = $nested->getBreadcrumbTitle();
            $nestedCrumbs[$nested->getListUrl()] = $nested->resource::getBreadcrumb();
             $nestedCrumbs[$nested->getViewUrl()] = $nested->resource::getBreadcrumb();
            }
            i want to add ViewUrl but             
            when i Tried to add it it shows
            Call to undefined method SevendaysDigital\FilamentNestedResources\NestedEntry::getViewUrl()

**Comment by haringsrob** [comment]
Hey! Would be nice if you could share more details on how to get here or by preference a small repository where the issue is reproduced.

**Comment by haringsrob** [comment]
Breadcrumbs for views should be fixed now.
